### ISSUE TITLE
Bootstrap is not working.

### ISSUE THREAD

**Issue by guptajeetesh7** [guptajeetesh7/Basic-Angular-4-Web-App#2]

**Comment by chrsi** [comment]
I can help you with that if you want :)

**Comment by guptajeetesh7** [comment]
Thanks a lot.

**Comment by chrsi** [comment]
You want to include the bootstrap ui library, am I right?

**Comment by guptajeetesh7** [comment]
Not ui library , simple bootstrap .

**Comment by chrsi** [comment]
Yeah I mean [bootstrap ](https://www.getbootstrap.com) not bootstrap as in the angular concept (since this seems to work fine)

**Comment by guptajeetesh7** [comment]
Yes ..

**Comment by adin234** [comment]
created a PR for this
